version: '2'

services:
        node-a:
                build: .
                links:
                        - node-b
                        - node-c
                        - node-d
                        - node-e
                        - node-f
                ports: 
                        - "8500:8500"
                        - "8300:8300"
                        - "8301:8301"
                        - "8302:8302"
        node-b:
                build: .
                ports: 
                        - "8501:8500"
                        - "8310:8300"
                        - "8311:8301"
                        - "8312:8302"
        node-c:
                build: .
                ports: 
                        - "8502:8500"
                        - "8320:8300"
                        - "8321:8301"
                        - "8322:8302"
        node-d:
                build: .
                links:
                        - node-b
                        - node-c
                        - node-e
                        - node-f
                command: /bin/consul agent -dc=dc2 -client 0.0.0.0 -server -data-dir /var/consul -bootstrap-expect 3
                ports: 
                        - "8505:8500"
                        - "8330:8300"
                        - "8331:8301"
                        - "8332:8302"
        node-e:
                build: .
                command: /bin/consul agent -dc=dc2 -client 0.0.0.0 -server -data-dir /var/consul -bootstrap-expect 3
                ports: 
                        - "8506:8500"
                        - "8340:8300"
                        - "8341:8301"
                        - "8342:8302"
        node-f:
                build: .
                command: /bin/consul agent -dc=dc2 -client 0.0.0.0 -server -data-dir /var/consul -bootstrap-expect 3
                ports: 
                        - "8507:8500"
                        - "8350:8300"
                        - "8351:8301"
                        - "8352:8302"
 
        agent-a:
                build: .
                links:
                        - node-a
                        - node-b
                        - node-c
                ports: 
                        - "8503:8500"
                command: /bin/consul agent -client 0.0.0.0 -data-dir /var/consul
        agent-b:
                build: .
                links:
                        - node-a
                        - node-b
                        - node-c
                ports: 
                        - "8504:8500"
                command: /bin/consul agent -client 0.0.0.0 -data-dir /var/consul
